/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.RDKit;
import java.util.Collections;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

public class RDProps {

	public static final Set<Long> OPEN_JAVA_OWNED_RDPROPS_PTRs = Collections.newSetFromMap(new ConcurrentHashMap<>());

  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected RDProps(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
    
    if (cMemoryOwn) {
    	OPEN_JAVA_OWNED_RDPROPS_PTRs.add(cPtr);
  	}
  }

  protected static long getCPtr(RDProps obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
    
    if (own) {
    	OPEN_JAVA_OWNED_RDPROPS_PTRs.add(swigCPtr);
    } else {
    	OPEN_JAVA_OWNED_RDPROPS_PTRs.remove(swigCPtr);
    }
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        System.err.println("DEBUG: [" + java.time.LocalDateTime.now() + "] Deleting " + this.getClass().getName()
                    + " (native ptr = 0x" + Long.toHexString(swigCPtr) + ")");
        swigCMemOwn = false;
        RDKFuncsJNI.delete_RDProps(swigCPtr);
        OPEN_JAVA_OWNED_RDPROPS_PTRs.remove(swigCPtr);
      } else {
        System.err.println("DEBUG: [" + java.time.LocalDateTime.now() + "] NOT Deleting " + this.getClass().getName()
                    + " (native ptr = 0x" + Long.toHexString(swigCPtr) + ") because swigCMemOwn is false. "
                    + "Owned by other Java object? " + OPEN_JAVA_OWNED_RDPROPS_PTRs.contains(swigCPtr));
      }
      swigCPtr = 0;
    }
  }

  public RDProps() {
    this(RDKFuncsJNI.new_RDProps__SWIG_0(), true);
  }

  public RDProps(RDProps rhs) {
    this(RDKFuncsJNI.new_RDProps__SWIG_1(RDProps.getCPtr(rhs), rhs), true);
  }

  public void clear() {
    RDKFuncsJNI.RDProps_clear(swigCPtr, this);
  }

  public Dict getDict() {
    return new Dict(RDKFuncsJNI.RDProps_getDict__SWIG_0(swigCPtr, this), false);
  }

  public Str_Vect getPropList(boolean includePrivate, boolean includeComputed) {
    return new Str_Vect(RDKFuncsJNI.RDProps_getPropList__SWIG_0(swigCPtr, this, includePrivate, includeComputed), true);
  }

  public Str_Vect getPropList(boolean includePrivate) {
    return new Str_Vect(RDKFuncsJNI.RDProps_getPropList__SWIG_1(swigCPtr, this, includePrivate), true);
  }

  public Str_Vect getPropList() {
    return new Str_Vect(RDKFuncsJNI.RDProps_getPropList__SWIG_2(swigCPtr, this), true);
  }

  public boolean hasProp(String key) {
    return RDKFuncsJNI.RDProps_hasProp(swigCPtr, this, key);
  }

  public void clearProp(String key) {
    RDKFuncsJNI.RDProps_clearProp(swigCPtr, this, key);
  }

  public void clearComputedProps() {
    RDKFuncsJNI.RDProps_clearComputedProps(swigCPtr, this);
  }

  public void updateProps(RDProps source, boolean preserveExisting) {
    RDKFuncsJNI.RDProps_updateProps__SWIG_0(swigCPtr, this, RDProps.getCPtr(source), source, preserveExisting);
  }

  public void updateProps(RDProps source) {
    RDKFuncsJNI.RDProps_updateProps__SWIG_1(swigCPtr, this, RDProps.getCPtr(source), source);
  }

  public void setProp(String key, String val, boolean computed) {
    RDKFuncsJNI.RDProps_setProp__SWIG_0(swigCPtr, this, key, val, computed);
  }

  public void setProp(String key, String val) {
    RDKFuncsJNI.RDProps_setProp__SWIG_1(swigCPtr, this, key, val);
  }

  public void setIntProp(String key, int val, boolean computed) {
    RDKFuncsJNI.RDProps_setIntProp__SWIG_0(swigCPtr, this, key, val, computed);
  }

  public void setIntProp(String key, int val) {
    RDKFuncsJNI.RDProps_setIntProp__SWIG_1(swigCPtr, this, key, val);
  }

  public void setBoolProp(String key, boolean val, boolean computed) {
    RDKFuncsJNI.RDProps_setBoolProp__SWIG_0(swigCPtr, this, key, val, computed);
  }

  public void setBoolProp(String key, boolean val) {
    RDKFuncsJNI.RDProps_setBoolProp__SWIG_1(swigCPtr, this, key, val);
  }

  public void setDoubleProp(String key, double val, boolean computed) {
    RDKFuncsJNI.RDProps_setDoubleProp__SWIG_0(swigCPtr, this, key, val, computed);
  }

  public void setDoubleProp(String key, double val) {
    RDKFuncsJNI.RDProps_setDoubleProp__SWIG_1(swigCPtr, this, key, val);
  }

  public void getStringProp(String key, SWIGTYPE_p_std__string res) {
    RDKFuncsJNI.RDProps_getStringProp__SWIG_0(swigCPtr, this, key, SWIGTYPE_p_std__string.getCPtr(res));
  }

  public String getStringProp(String key) {
    return RDKFuncsJNI.RDProps_getStringProp__SWIG_1(swigCPtr, this, key);
  }

  public void getUIntProp(String key, SWIGTYPE_p_unsigned_int res) {
    RDKFuncsJNI.RDProps_getUIntProp__SWIG_0(swigCPtr, this, key, SWIGTYPE_p_unsigned_int.getCPtr(res));
  }

  public long getUIntProp(String key) {
    return RDKFuncsJNI.RDProps_getUIntProp__SWIG_1(swigCPtr, this, key);
  }

  public void getStringVectProp(String key, Str_Vect res) {
    RDKFuncsJNI.RDProps_getStringVectProp__SWIG_0(swigCPtr, this, key, Str_Vect.getCPtr(res), res);
  }

  public Str_Vect getStringVectProp(String key) {
    return new Str_Vect(RDKFuncsJNI.RDProps_getStringVectProp__SWIG_1(swigCPtr, this, key), true);
  }

  public void getUIntVectProp(String key, UInt_Vect res) {
    RDKFuncsJNI.RDProps_getUIntVectProp__SWIG_0(swigCPtr, this, key, UInt_Vect.getCPtr(res), res);
  }

  public UInt_Vect getUIntVectProp(String key) {
    return new UInt_Vect(RDKFuncsJNI.RDProps_getUIntVectProp__SWIG_1(swigCPtr, this, key), true);
  }

}
